theme: jekyll-theme-slate

# site settings
title: [Will Marringa]
description: [Masters of Software Development Student @ University of Utah]

#Buzzwords
skills:
  - C/C++
  - Python
  - Java
  - C#
  - MySQL

